### ISSUE TITLE
Wrongs Save Stations

### ISSUE THREAD

**Issue by RASK18** [wildryce/Arcadia-Interactive-Map#1]
![image](https://user-images.githubusercontent.com/16093842/206267019-19b4cb1a-ed81-4fe8-a3b1-175625cb2eae.png)
![image](https://user-images.githubusercontent.com/16093842/206274620-aadc1c13-3f7b-4112-91a0-87b69c4d1109.png)
![image](https://user-images.githubusercontent.com/16093842/206275122-1c1b21e3-565d-43c6-bdc8-2eb0aaffd835.png)
![image](https://user-images.githubusercontent.com/16093842/206283114-dbda543a-bf0c-4ca9-812f-6b21a25de4e6.png)
![image](https://user-images.githubusercontent.com/16093842/206284075-ad3c4496-4e2f-4ccb-b44d-61fcbd08d5ca.png)
![image](https://user-images.githubusercontent.com/16093842/206285925-74d6fe57-ddeb-48d4-b9b5-f9399553625a.png)
![image](https://user-images.githubusercontent.com/16093842/206292149-58e02d24-e454-46df-80b2-bcc140ef0929.png)
![image](https://user-images.githubusercontent.com/16093842/206292373-026e1a2a-ba88-4f8d-b40d-2ccf96a2e8cc.png)
![image](https://user-images.githubusercontent.com/16093842/206295221-a43a44c0-cbc1-42df-a6bc-e4330fa4a071.png)
![image](https://user-images.githubusercontent.com/16093842/206304596-e2eb8199-9170-4279-b84a-d7690262848c.png)

**Comment by wildryce** [comment]
Thank you for the issue input here! The couple save stations that existed weren't supposed to exist at the time (they were for making sure the sizing and such were correct) so that is why they were mainly out of place minus the one in Wastes. Finally got the time to fix this and properly add all the save stations, so everything should be set unless I do minor placement adjustments.
